services:
  syncthing:
    image: syncthing/syncthing:latest
    container_name: lilith-obsidian-syncthing
    hostname: lilith-obsidian-syncthing
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ${VAULT_PATH}:/var/syncthing/vault
      - syncthing-config:/var/syncthing/config
    networks:
      - lilith_default

volumes:
  syncthing-config:

networks:
  lilith_default:
    name: lilith_default
    external: true
