# Para reativar: copie este bloco para lilith/nginx/nginx.conf
# e certifique-se que o serviço 'webserver' está na rede lilith_default.

server {
    listen 80;
    server_name paper.lilith.hell library.lilith.hell paperless.lilith.hell;

    access_log /var/log/nginx/paperless_access.log;
    error_log  /var/log/nginx/paperless_error.log;

    location / {
        resolver 127.0.0.11 valid=10s;
        set $backend_service "webserver:8000";

        include snippets/proxy_params_immich.conf;
        proxy_pass http://$backend_service;
    }

    location /health {
        access_log off;
        return 200 "healthy\n";
    }
}
