services:
  syncthing:
    image: syncthing/syncthing:latest
    container_name: syncthing
    hostname: lilith-syncthing
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ${VAULT_PATH}:/var/syncthing/vault
      - ${ARCANE}/syncthing/.data:/var/syncthing/config
    networks:
      - lilith_default

networks:
  lilith_default:
    name: lilith_default
    external: true
