services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    networks:
      - proxy_net
    expose:
      - '11434'
    tty: true
    stdin_open: true
    env_file:
      - .env
    volumes:
      - ${ARCANE}/ollama/.data:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped

networks:
  proxy_net:
    name: proxy_net
    external: true
