services:
  zotero:
    build:
      context: .
    image: zotero-webdav:local
    pull_policy: never
    container_name: zotero  
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ${ARCANE}/zotero/.data:/var/lib/dav/data
    networks:
      - asmodeus_default

networks:
  asmodeus_default:
    name: asmodeus_default
    external: true