services:
  zotero-webdav:
    image: bytemark/webdav:latest
    container_name: webdav
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ${ARCANE}/zotero/.data:/var/lib/dav/data
    networks:
      - asmodeus_default

networks:
  asmodeus_default:
    name: asmodeus_default
    external: true
