OVERLEAF_APP_NAME="MyLatex"
EMAIL_CONFIRMATION_DISABLED=true
ENABLE_CONVERSIONS=true
ENABLED_LINKED_FILE_TYPES=project_file,project_output_file
EXTERNAL_AUTH=none

# --- Conexões com os Serviços ---
# CORREÇÃO CRÍTICA: Adicionado o parâmetro para informar o nome do Replica Set
OVERLEAF_MONGO_URL=mongodb://mongo/sharelatex?replicaSet=overleaf

OVERLEAF_REDIS_HOST=redis
REDIS_HOST=redis
REDIS_PORT=6379