services:
  arcane:
    image: ghcr.io/ofkm/arcane:latest
    container_name: asmodeus-arcane
    ports:
      - '3552:3552'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${ARCANE}/arcane_data:/app/data
      - ${ARCANE}:${ARCANE}
    environment:
      - PROJECTS_DIRECTORY=${ARCANE}
    restart: unless-stopped
    env_file:
      - .env
