services:
  arcane:
    image: ghcr.io/ofkm/arcane:latest
    container_name: arcane
    ports:
      - '3552:3552'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${ARCANE}/.data:/app/data
      - ${ARCANE}:/app/data/projects
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - asmodeus_default

networks:
  asmodeus_default:
    name: asmodeus_default
    driver: bridge
