#!/bin/bash
# restore.sh — Restore Immich from a dump.sh snapshot
# Usage: ./restore.sh [backup_dir]
#
# If no backup_dir is given, uses the most recent backup in <project>/.backup/
#
# What it does:
#   1. Reads manifest.json and .env.restore from the backup
#   2. Generates docker-compose.override.yaml inside the backup dir, pinning exact image digests
#   3. Starts only the database, waits for healthy
#   4. Restores pg_dumpall.sql
#   5. Starts remaining services
#   6. Validates all healthchecks
#
# Prerequisites:
#   - UPLOAD_LOCATION and DB_DATA_LOCATION paths must exist on the target device
#   - Docker and docker compose available
#   - No conflicting containers running on the same ports

set -euo pipefail

# --- Context resolution ---
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
COMPOSE_FILE="$PROJECT_DIR/compose.yaml"

if [[ ! -f "$COMPOSE_FILE" ]]; then
    echo "[error] compose.yaml not found at $PROJECT_DIR" >&2
    exit 1
fi

# --- Resolve backup directory ---
if [[ -n "${1:-}" ]]; then
    BACKUP_DIR="$1"
else
    # Find most recent backup
    BACKUP_BASE="$PROJECT_DIR/.backup"
    if [[ ! -d "$BACKUP_BASE" ]]; then
        echo "[error] No .backup/ directory found and no backup path given" >&2
        exit 1
    fi
    BACKUP_DIR=$(find "$BACKUP_BASE" -mindepth 1 -maxdepth 1 -type d | sort -r | head -1)
    if [[ -z "$BACKUP_DIR" ]]; then
        echo "[error] No backups found in $BACKUP_BASE" >&2
        exit 1
    fi
    echo "[restore] Using most recent backup: $BACKUP_DIR"
fi

# --- Validate backup contents ---
MANIFEST="$BACKUP_DIR/manifest.json"
SQL_DUMP="$BACKUP_DIR/pg_dumpall.sql"
ENV_RESTORE="$BACKUP_DIR/.env.restore"
OVERRIDE_FILE="$BACKUP_DIR/docker-compose.override.yaml"

for f in "$MANIFEST" "$SQL_DUMP" "$ENV_RESTORE"; do
    if [[ ! -f "$f" ]]; then
        echo "[error] Missing required file: $f" >&2
        exit 1
    fi
done

echo "[restore] Backup contents:"
ls -lh "$BACKUP_DIR/"
echo ""

# --- Read manifest ---
BACKUP_TIMESTAMP=$(python3 -c "import json; m=json.load(open('$MANIFEST')); print(m['timestamp'])")
PG_VERSION=$(python3 -c "import json; m=json.load(open('$MANIFEST')); print(m.get('postgres_version','unknown'))")
echo "[restore] Backup from: $BACKUP_TIMESTAMP"
echo "[restore] PostgreSQL version: $PG_VERSION"

# --- Check .env ---
# Use .env.restore as the active .env if no .env exists, otherwise warn about differences
ENV_FILE="$PROJECT_DIR/.env"
if [[ ! -f "$ENV_FILE" ]]; then
    echo "[restore] No .env found — copying .env.restore"
    cp "$ENV_RESTORE" "$ENV_FILE"
else
    if ! diff -q "$ENV_FILE" "$ENV_RESTORE" &>/dev/null; then
        echo "[warn] Current .env differs from backup .env.restore"
        echo "[warn] Critical vars to check: DB_PASSWORD, DB_USERNAME, DB_DATABASE_NAME"
        echo "[warn] Data path vars to check: UPLOAD_LOCATION, DB_DATA_LOCATION, MODEL_DIR"
        echo ""
        diff --color=auto "$ENV_RESTORE" "$ENV_FILE" || true
        echo ""
        read -rp "Continue with CURRENT .env? (y/N) " confirm
        if [[ "$confirm" != "y" && "$confirm" != "Y" ]]; then
            echo "[restore] Aborted. Review .env and .env.restore, then retry."
            exit 1
        fi
    fi
fi

# --- Load env and validate paths ---
set -a
# shellcheck disable=SC1090
source "$ENV_FILE"
set +a

DB_USER="${DB_USERNAME:-postgres}"

MISSING_PATHS=false
for varname in UPLOAD_LOCATION DB_DATA_LOCATION; do
    path="${!varname:-}"
    if [[ -z "$path" ]]; then
        echo "[error] $varname is not set in .env" >&2
        MISSING_PATHS=true
    elif [[ ! -d "$path" ]]; then
        echo "[warn] $varname=$path does not exist on this device"
        read -rp "Create it? (y/N) " create
        if [[ "$create" == "y" || "$create" == "Y" ]]; then
            mkdir -p "$path"
            echo "[restore] Created $path"
        else
            MISSING_PATHS=true
        fi
    fi
done

if $MISSING_PATHS; then
    echo "[error] Cannot proceed with missing data paths" >&2
    exit 1
fi

# --- Generate override with pinned images ---
echo "[restore] Generating image-pinned override..."

# Extract image digests from manifest
read_image() {
    python3 -c "
import json, sys
m = json.load(open('$MANIFEST'))
svc = m.get('services', {}).get('$1', {})
print(svc.get('image', ''))
"
}

SERVER_IMAGE=$(read_image "immich-server")
ML_IMAGE=$(read_image "immich-machine-learning")
REDIS_IMAGE=$(read_image "redis")
DB_IMAGE=$(read_image "database")

cat > "$OVERRIDE_FILE" <<EOF
# AUTO-GENERATED by restore.sh — DO NOT COMMIT
# Pins images to exact versions from backup $BACKUP_TIMESTAMP
# Safe to delete after successful restore and verification.
services:
  immich-server:
    image: $SERVER_IMAGE
  immich-machine-learning:
    image: $ML_IMAGE
  redis:
    image: $REDIS_IMAGE
  database:
    image: $DB_IMAGE
EOF

echo "[restore] Override written: $OVERRIDE_FILE"
echo ""

# --- Ensure no conflicting containers ---
echo "[restore] Stopping any existing Immich containers..."
docker compose -f "$COMPOSE_FILE" -f "$OVERRIDE_FILE" --env-file "$ENV_FILE" down 2>/dev/null || true
echo ""

# --- Clear DB_DATA_LOCATION for clean restore ---
if [[ -d "$DB_DATA_LOCATION" ]] && [[ "$(ls -A "$DB_DATA_LOCATION" 2>/dev/null)" ]]; then
    echo "[warn] DB_DATA_LOCATION ($DB_DATA_LOCATION) is not empty."
    echo "[warn] For a clean restore, this directory should be empty."
    echo "[warn] The existing data will be REPLACED by the dump."
    read -rp "Clear it and proceed? (y/N) " clear_db
    if [[ "$clear_db" == "y" || "$clear_db" == "Y" ]]; then
        rm -rf "${DB_DATA_LOCATION:?}/"*
        echo "[restore] Cleared $DB_DATA_LOCATION"
    else
        echo "[warn] Proceeding without clearing — restore may fail if data conflicts exist"
    fi
fi

# --- Step 1: Start database only ---
echo "[restore] Starting database..."
docker compose -f "$COMPOSE_FILE" -f "$OVERRIDE_FILE" --env-file "$ENV_FILE" up -d database

echo "[restore] Waiting for PostgreSQL to be ready..."
RETRIES=30
until docker compose -f "$COMPOSE_FILE" -f "$OVERRIDE_FILE" --env-file "$ENV_FILE" \
    exec -T database pg_isready -U "$DB_USER" &>/dev/null; do
    ((RETRIES--)) || {
        echo "[error] PostgreSQL did not become ready in time" >&2
        exit 1
    }
    sleep 2
done
echo "[restore] PostgreSQL is ready"

# --- Step 2: Restore dump ---
echo "[restore] Restoring database from dump..."
docker compose -f "$COMPOSE_FILE" -f "$OVERRIDE_FILE" --env-file "$ENV_FILE" \
    exec -T database psql -U "$DB_USER" < "$SQL_DUMP"
echo "[restore] Database restored"

# --- Step 3: Start remaining services ---
echo "[restore] Starting all services..."
docker compose -f "$COMPOSE_FILE" -f "$OVERRIDE_FILE" --env-file "$ENV_FILE" up -d

# --- Step 4: Validate healthchecks ---
echo "[restore] Waiting for services to become healthy..."
sleep 5

ALL_HEALTHY=true
for service in immich-server immich-machine-learning redis database; do
    container=$(docker compose -f "$COMPOSE_FILE" -f "$OVERRIDE_FILE" --env-file "$ENV_FILE" \
        ps --format '{{.Name}}' "$service" 2>/dev/null || true)

    if [[ -z "$container" ]]; then
        echo "  $service: not found"
        ALL_HEALTHY=false
        continue
    fi

    # Wait up to 60s for this container
    RETRIES=12
    status="unknown"
    while [[ $RETRIES -gt 0 ]]; do
        status=$(docker inspect "$container" --format '{{.State.Health.Status}}' 2>/dev/null || echo "no-healthcheck")
        if [[ "$status" == "healthy" || "$status" == "no-healthcheck" ]]; then
            break
        fi
        ((RETRIES--))
        sleep 5
    done

    echo "  $service ($container): $status"
    if [[ "$status" != "healthy" && "$status" != "no-healthcheck" ]]; then
        ALL_HEALTHY=false
    fi
done

echo ""

if $ALL_HEALTHY; then
    echo "=== Restore complete ==="
    echo ""
    echo "All services are healthy. Verify your data in the Immich UI."
    echo ""
    echo "Once confirmed working, restart without the override:"
    echo "  docker compose -f $COMPOSE_FILE --env-file $ENV_FILE down"
    echo "  docker compose -f $COMPOSE_FILE --env-file $ENV_FILE up -d"
    echo ""
    echo "Override preserved in backup: $OVERRIDE_FILE"
else
    echo "=== Restore completed with warnings ==="
    echo ""
    echo "Some services may not be healthy. Check logs:"
    echo "  docker compose -f $COMPOSE_FILE -f $OVERRIDE_FILE --env-file $ENV_FILE logs"
    echo ""
    echo "Override preserved in backup: $OVERRIDE_FILE"
fi
