# Para reativar: copie este bloco para lilith/nginx/nginx.conf
# e certifique-se que o serviço 'jellyfin' está na rede lilith_default.

server {
    listen 80;
    server_name metflix.lilith.hell netflix.lilith.hell jellyfin.lilith.hell;

    access_log /var/log/nginx/jellyfin_access.log;
    error_log  /var/log/nginx/jellyfin_error.log;

    location / {
        resolver 127.0.0.11 valid=10s;
        set $backend_service "jellyfin:8096";

        include snippets/proxy_params_immich.conf;
        proxy_pass http://$backend_service;
    }

    location /health {
        access_log off;
        return 200 "healthy\n";
    }
}
