services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      #- ${ARCANE_DIR}/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      #- ${ARCANE_DIR}/nginx/logs:/var/log/nginx
      #- ${ARCANE_DIR}/nginx/www:/var/www
      #- ${ARCANE_DIR}/nginx/snippets:/etc/nginx/snippets
      - ${NGINX_DIR}/nginx.conf:/etc/nginx/conf.d/default.conf
      - ${NGINX_DIR}/logs:/var/log/nginx
      - ${NGINX_DIR}/www:/var/www
      - ${NGINX_DIR}/snippets:/etc/nginx/snippets
    networks:
      - lilith_default
    restart: unless-stopped
    stdin_open: true
    tty: true  

networks:
  lilith_default:
    name: lilith_default
    external: true
