server {
    listen 80 default_server;
    
    root /var/www/default_page;

    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    access_log /var/log/nginx/default_access.log;
    error_log /var/log/nginx/default_error.log;
}

server {
    listen 80;
    server_name arcane.lilith.hell;
    
    access_log /var/log/nginx/arcane_access.log;
    error_log /var/log/nginx/arcane_error.log;
    
    location / {
        # Inclui todas as configurações de proxy do nosso snippet
        include snippets/proxy_params.conf;
        proxy_pass http://arcane:3552;
    }
    
    location /health {
        access_log off;
        return 200 "healthy\n";
    }
}

server {
    listen 80;
    server_name btop.lilith.hell;

    access_log /var/log/nginx/btop_access.log;
    error_log /var/log/nginx/btop_error.log;
    
    location / {
        include snippets/proxy_params.conf;
        proxy_pass http://btop:8686;
    }
    
    location /health {
        access_log off;
        return 200 "healthy\n";
    }
}
