services:
  webdav-init:
    image: bytemark/webdav:latest
    container_name: webdav-init
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        mkdir -p /var/lib/dav/data/zotero
        chown -R www-data:www-data /var/lib/dav/data || true
        chmod -R 777 /var/lib/dav/data
    volumes:
      - ${ARCANE}/webdav/.data:/var/lib/dav/data
    restart: "no"

  webdav:
    image: bytemark/webdav:latest
    container_name: webdav
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ${ARCANE}/webdav/.data:/var/lib/dav/data
    networks:
      - asmodeus_default
    depends_on:
      webdav-init:
        condition: service_completed_successfully

networks:
  asmodeus_default:
    name: asmodeus_default
    external: true
