services:
  btop:
    build: .
    container_name: btop
    restart: unless-stopped
    pid: "host"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
    expose:
      - '8686'
    networks:
      - proxy_net
    stdin_open: true
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

networks:
  proxy_net:
    name: proxy_net
    external: true
